# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for pipenv
  - package-ecosystem: "pipenv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
     # if weekly is selected, day can be alterted to make maintenance
      interval: "weekly"
      day: "sunday"
      time: "11:00"
      timezone: "Europe/London"

  
  # Maintain dependencies for pip
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "11:00"
      timezone: "Europe/London"
